package com.mit.entity;

// Generated 30 avr. 2016 14:36:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attestation generated by hbm2java
 */
@Entity
@Table(name = "attestation", catalog = "mitdb")
public class Attestation implements java.io.Serializable {

	private Integer idAttestation;
	private Membre membre;
	private Projet projet;
	private Date dateAttestation;
	private String descAttestation;
	private String attribut35;

	public Attestation() {
	}

	public Attestation(Membre membre, Projet projet) {
		this.membre = membre;
		this.projet = projet;
	}

	public Attestation(Membre membre, Projet projet, Date dateAttestation,
			String descAttestation, String attribut35) {
		this.membre = membre;
		this.projet = projet;
		this.dateAttestation = dateAttestation;
		this.descAttestation = descAttestation;
		this.attribut35 = attribut35;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAttestation", unique = true, nullable = false)
	public Integer getIdAttestation() {
		return this.idAttestation;
	}

	public void setIdAttestation(Integer idAttestation) {
		this.idAttestation = idAttestation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMembre", nullable = false)
	public Membre getMembre() {
		return this.membre;
	}

	public void setMembre(Membre membre) {
		this.membre = membre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProjet", nullable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateAttestation", length = 10)
	public Date getDateAttestation() {
		return this.dateAttestation;
	}

	public void setDateAttestation(Date dateAttestation) {
		this.dateAttestation = dateAttestation;
	}

	@Column(name = "descAttestation", length = 254)
	public String getDescAttestation() {
		return this.descAttestation;
	}

	public void setDescAttestation(String descAttestation) {
		this.descAttestation = descAttestation;
	}

	@Column(name = "Attribut_35", length = 10)
	public String getAttribut35() {
		return this.attribut35;
	}

	public void setAttribut35(String attribut35) {
		this.attribut35 = attribut35;
	}

}
