package com.mit.entity;

// Generated 20 avr. 2016 13:30:11 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "mitdb")
public class Contrat implements java.io.Serializable {

	private int idContrat;
	private Contrattache contrattache;
	private Contratprojet contratprojet;

	public Contrat() {
	}

	public Contrat(int idContrat) {
		this.idContrat = idContrat;
	}

	public Contrat(int idContrat, Contrattache contrattache,
			Contratprojet contratprojet) {
		this.idContrat = idContrat;
		this.contrattache = contrattache;
		this.contratprojet = contratprojet;
	}

	@Id
	@Column(name = "idContrat", unique = true, nullable = false)
	public int getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(int idContrat) {
		this.idContrat = idContrat;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "contrat")
	public Contrattache getContrattache() {
		return this.contrattache;
	}

	public void setContrattache(Contrattache contrattache) {
		this.contrattache = contrattache;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "contrat")
	public Contratprojet getContratprojet() {
		return this.contratprojet;
	}

	public void setContratprojet(Contratprojet contratprojet) {
		this.contratprojet = contratprojet;
	}

}
