package com.mit.entity;

// Generated 25 avr. 2016 17:35:48 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "mitdb")
public class Contrat implements java.io.Serializable {

	private Integer idContrat;
	private Contrattache contrattache;
	private Contratprojet contratprojet;

	public Contrat() {
	}

	public Contrat(Contrattache contrattache, Contratprojet contratprojet) {
		this.contrattache = contrattache;
		this.contratprojet = contratprojet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idContrat", unique = true, nullable = false)
	public Integer getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(Integer idContrat) {
		this.idContrat = idContrat;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "contrat")
	public Contrattache getContrattache() {
		return this.contrattache;
	}

	public void setContrattache(Contrattache contrattache) {
		this.contrattache = contrattache;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "contrat")
	public Contratprojet getContratprojet() {
		return this.contratprojet;
	}

	public void setContratprojet(Contratprojet contratprojet) {
		this.contratprojet = contratprojet;
	}

}
