package com.mit.entity;

// Generated 30 avr. 2016 14:36:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "mitdb")
public class Contrat implements java.io.Serializable {

	private Integer idContrat;
	private Societe societe;
	private Membre membre;
	private Tache tache;
	private Projet projet;
	private Date dateContrat;
	private Float cout;
	private Date debutContrat;
	private Date finContrat;
	private String typeContrat;

	public Contrat() {
	}

	public Contrat(Societe societe, Membre membre, Tache tache, Projet projet) {
		this.societe = societe;
		this.membre = membre;
		this.tache = tache;
		this.projet = projet;
	}

	public Contrat(Societe societe, Membre membre, Tache tache, Projet projet,
			Date dateContrat, Float cout, Date debutContrat, Date finContrat,
			String typeContrat) {
		this.societe = societe;
		this.membre = membre;
		this.tache = tache;
		this.projet = projet;
		this.dateContrat = dateContrat;
		this.cout = cout;
		this.debutContrat = debutContrat;
		this.finContrat = finContrat;
		this.typeContrat = typeContrat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idContrat", unique = true, nullable = false)
	public Integer getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(Integer idContrat) {
		this.idContrat = idContrat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSociete", nullable = false)
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMembre", nullable = false)
	public Membre getMembre() {
		return this.membre;
	}

	public void setMembre(Membre membre) {
		this.membre = membre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTache", nullable = false)
	public Tache getTache() {
		return this.tache;
	}

	public void setTache(Tache tache) {
		this.tache = tache;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProjet", nullable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateContrat", length = 10)
	public Date getDateContrat() {
		return this.dateContrat;
	}

	public void setDateContrat(Date dateContrat) {
		this.dateContrat = dateContrat;
	}

	@Column(name = "cout", precision = 12, scale = 0)
	public Float getCout() {
		return this.cout;
	}

	public void setCout(Float cout) {
		this.cout = cout;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "debutContrat", length = 10)
	public Date getDebutContrat() {
		return this.debutContrat;
	}

	public void setDebutContrat(Date debutContrat) {
		this.debutContrat = debutContrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finContrat", length = 10)
	public Date getFinContrat() {
		return this.finContrat;
	}

	public void setFinContrat(Date finContrat) {
		this.finContrat = finContrat;
	}

	@Column(name = "typeContrat", length = 254)
	public String getTypeContrat() {
		return this.typeContrat;
	}

	public void setTypeContrat(String typeContrat) {
		this.typeContrat = typeContrat;
	}

}
