package com.mit.entity;

// Generated 20 avr. 2016 13:30:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Contratprojet generated by hbm2java
 */
@Entity
@Table(name = "contratprojet", catalog = "mitdb")
public class Contratprojet implements java.io.Serializable {

	private int idContrat;
	private Societe societe;
	private Contrat contrat;
	private Projet projet;
	private Integer cout;
	private Date dateDebut;
	private Date dateFin;

	public Contratprojet() {
	}

	public Contratprojet(Societe societe, Contrat contrat, Projet projet) {
		this.societe = societe;
		this.contrat = contrat;
		this.projet = projet;
	}

	public Contratprojet(Societe societe, Contrat contrat, Projet projet,
			Integer cout, Date dateDebut, Date dateFin) {
		this.societe = societe;
		this.contrat = contrat;
		this.projet = projet;
		this.cout = cout;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "contrat"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idContrat", unique = true, nullable = false)
	public int getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(int idContrat) {
		this.idContrat = idContrat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSociete", nullable = false)
	public Societe getSociete() {
		return this.societe;
	}

	public void setSociete(Societe societe) {
		this.societe = societe;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProjet", nullable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "cout", precision = 8, scale = 0)
	public Integer getCout() {
		return this.cout;
	}

	public void setCout(Integer cout) {
		this.cout = cout;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateDebut", length = 0)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateFin", length = 0)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
