package com.mit.entity;

// Generated 30 avr. 2016 14:36:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TachemembreId generated by hbm2java
 */
@Embeddable
public class TachemembreId implements java.io.Serializable {

	private int idTache;
	private String idMembre;

	public TachemembreId() {
	}

	public TachemembreId(int idTache, String idMembre) {
		this.idTache = idTache;
		this.idMembre = idMembre;
	}

	@Column(name = "idTache", nullable = false)
	public int getIdTache() {
		return this.idTache;
	}

	public void setIdTache(int idTache) {
		this.idTache = idTache;
	}

	@Column(name = "idMembre", nullable = false, length = 254)
	public String getIdMembre() {
		return this.idMembre;
	}

	public void setIdMembre(String idMembre) {
		this.idMembre = idMembre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TachemembreId))
			return false;
		TachemembreId castOther = (TachemembreId) other;

		return (this.getIdTache() == castOther.getIdTache())
				&& ((this.getIdMembre() == castOther.getIdMembre()) || (this
						.getIdMembre() != null
						&& castOther.getIdMembre() != null && this
						.getIdMembre().equals(castOther.getIdMembre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTache();
		result = 37 * result
				+ (getIdMembre() == null ? 0 : this.getIdMembre().hashCode());
		return result;
	}

}
