package com.mit.entity;

// Generated 25 avr. 2016 17:35:48 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TacheId generated by hbm2java
 */
@Embeddable
public class TacheId implements java.io.Serializable {

	private int idProjet;
	private int idTache;

	public TacheId() {
	}

	public TacheId(int idProjet, int idTache) {
		this.idProjet = idProjet;
		this.idTache = idTache;
	}

	@Column(name = "idProjet", nullable = false)
	public int getIdProjet() {
		return this.idProjet;
	}

	public void setIdProjet(int idProjet) {
		this.idProjet = idProjet;
	}

	@Column(name = "idTache", nullable = false)
	public int getIdTache() {
		return this.idTache;
	}

	public void setIdTache(int idTache) {
		this.idTache = idTache;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TacheId))
			return false;
		TacheId castOther = (TacheId) other;

		return (this.getIdProjet() == castOther.getIdProjet())
				&& (this.getIdTache() == castOther.getIdTache());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProjet();
		result = 37 * result + this.getIdTache();
		return result;
	}

}
